- name: Fact | vhost_directory
  set_fact: vhost_directory=/var/www/{{ vhost_domain }}

- name: Fact | apache etc
  set_fact: apache_etc=/etc/apache2

- name: Fact | apache sites-available
  set_fact: apache_sites_available={{ apache_etc }}/sites-available

- name: Fact | apache sites-enabled
  set_fact: apache_sites_enabled={{ apache_etc }}/sites-enabled

- name: Ensure apache sites-available/sites-enabled exists
  file: path={{ item }} owner=root group=root mode=0755
  with_items:
    - "{{ apache_sites_enabled }}"
    - "{{ apache_sites_available }}"

- name: Create vhost directory
  file: path={{ vhost_directory }} owner=root group=root mode=0755 state=directory

- name: Create vhost user
  user: name={{ vhost_user }} createhome=no home={{ vhost_directory }} shell=/bin/false

- name: Add www-data to users group
  user: name=www-data append=yes groups={{ vhost_user }}

- name: Create htdocs
  file: path={{ vhost_directory }}/htdocs owner={{ vhost_user }} group={{ vhost_user }} mode=0750 state=directory

- name: Create log directory
  file: path={{ vhost_directory }}/logs owner=root group={{ vhost_user }} mode=0750 state=directory

- name: Create tmp directory
  file: path={{ vhost_directory }}/tmp owner={{ vhost_user }} group={{ vhost_user }} mode=0700 state=directory

# Workaround: include_role has problems with when in 2.2
- block:
  - name: PHP
    include_role: name=php
    static: no
  when: use_php

- name: Apache configuration
  template: src=vhost.conf.j2 dest={{ apache_sites_available }}/{{ vhost_domain }}.conf owner=root group=root mode=0644

- name: Enable Apache configuration
  file: state=link src={{ apache_sites_available }}/{{ vhost_domain }}.conf path={{ apache_sites_enabled }}/{{ vhost_domain }}.conf

