- name: Fact | vhost_directory
  set_fact: vhost_directory=/var/www/{{ vhost_domain }}

- name: Fact | apache etc
  set_fact: apache_etc=/etc/apache2

- name: Fact | apache sites-available
  set_fact: apache_sites_available={{ apache_etc }}/sites-available

- name: Fact | apache sites-enabled
  set_fact: apache_sites_enabled={{ apache_etc }}/sites-enabled

- name: Fact | apache sites-include
  set_fact: apache_sites_include={{ apache_etc }}/sites-include

- name: Fact | vhost_user_home
  set_fact: vhost_user_home={{ vhost_directory }}
  when: not vhost_user_home is defined

- name: Create site-include directory
  file: path={{ apache_sites_include }} owner=root group=root mode=0755 state=directory

- name: Ensure apache sites-available/sites-enabled exists
  file: path={{ item }} owner=root group=root mode=0755
  with_items:
    - "{{ apache_sites_enabled }}"
    - "{{ apache_sites_available }}"

- name: Create vhost directory
  file: path={{ vhost_directory }} owner=root group=root mode=0755 state=directory

- name: Create vhost user
  user: name={{ vhost_user }} createhome=no home={{ vhost_user_home }} shell={{vhost_user_shell}}

- name: Add www-data to users group
  user: name=www-data append=yes groups={{ vhost_user }}

- name: Check if bash_history exists
  stat: path={{ vhost_directory }}/.bash_history
  register: stat_bash_history

- name: Create bash history file
  file: path={{ vhost_directory }}/.bash_history state="touch"
  when: vhost_user_bash_files and not stat_bash_history.stat.exists

- name: Set bash history permissions
  file: path={{ vhost_directory }}/.bash_history owner={{ vhost_user }} group={{ vhost_user }} mode=0640
  when: stat_bash_history.stat.exists

- name: Check if bashrc exists
  stat: path={{ vhost_directory }}/.bashrc
  register: stat_bashrc

- name: Create bashrc file
  file: path={{ vhost_directory }}/.bashrc state="touch"
  when: vhost_user_bash_files and not stat_bashrc.stat.exists

- name: Set bashrc permissions
  file: path={{ vhost_directory }}/.bashrc owner={{ vhost_user }} group={{ vhost_user }} mode=0640
  when: stat_bashrc.stat.exists

- name: Check if .viminfo exists
  stat: path={{ vhost_directory }}/.viminfo
  register: stat_viminfo

- name: Create .viminfo
  file: path={{ vhost_directory }}/.viminfo state="touch"
  when: vhost_user_bash_files and not stat_viminfo.stat.exists

- name: Set .viminfo permissions
  file: path={{ vhost_directory }}/.viminfo owner={{ vhost_user }} group={{ vhost_user }} mode=0640
  when: stat_viminfo.stat.exists

- name: Create htdocs
  file: path={{ vhost_directory }}/htdocs owner={{ vhost_user }} group={{ vhost_user }} mode=0750 state=directory

- name: Create log directory
  file: path={{ vhost_directory }}/logs owner=root group={{ vhost_user }} mode=0750 state=directory

- name: Create tmp directory
  file: path={{ vhost_directory }}/tmp owner={{ vhost_user }} group={{ vhost_user }} mode=0700 state=directory

# Workaround: include_role has problems with when in 2.2
- block:
  - name: PHP
    include_role: name=php
    static: no
  when: use_php

- name: Apache install mod_perl
  apt: name=libapache2-mod-perl2
  when: use_perl

- name: Apache configuration
  template: src=vhost.conf.j2 dest={{ apache_sites_available }}/{{ vhost_domain }}.conf owner=root group=root mode=0644

- name: Enable Apache configuration
  file: state=link src={{ apache_sites_available }}/{{ vhost_domain }}.conf path={{ apache_sites_enabled }}/{{ vhost_domain }}.conf
